keys:
  - &isabel age1w98qzycsw5jk9hpy4yg5ld05qqdvs2vxctdypx0tqppvxrk579yshzctus
  - &hydra age1dfcv3m85krzqya9tsft5hwrapl3zq35ry6zrt8gy92afcyrrau6q879rfc
  - &luz age1c28zh0wrj567uzhj8echy684srjgcpksj0c6m0rhjx09wcxgtp8sxdyw4q
  - &valkyrie age1e9thqqupjlm6hfpjjwamt9rzyxuuqrrpd5vtxj0mxnpaec4lk5vqwf09zl
creation_rules:
  - path_regex: modules/base/secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *isabel
          - *hydra
          - *luz
          - *valkyrie
