name: Validate Nix Flake
description: "Check the Nix flake for errors"

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Lix
      uses: ./.github/actions/install-lix

    - name: Check Flake
      shell: bash
      run: nix flake check --option allow-import-from-derivation false
