name: Build and Release ISO Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 1,15 * *" # Run on the 1st and 15th of every month at 3:00 AM

jobs:
  build-isos:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize Space
        uses: easimon/maximize-build-space@v10
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-codeql: true
          remove-haskell: true
          remove-docker-images: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Build Lilith Iso
        continue-on-error: false
        run: nix build .#images.lilith -o lilith --accept-flake-config --print-build-logs

      - name: Remove old ISOs
        run: gh release view isos | rg "asset" | awk '{print $2}' | xargs -I {} gh release delete isos {}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload Release Artifacts
        run: gh release upload --clobber isos ./lilith/iso/*.iso
        env:
          GH_TOKEN: ${{ github.token }}
