name: Build and populate cache

on:
  workflow_dispatch:
  push:
    paths:
      - "flake/pkgs"
      - "**.lock"
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - bellado
          - isabelroses-website
          - catppuccinifier-cli
          - lutgen-rs
          - patched-gjs
          - plymouth-theme-catppuccin

    steps:
      - name: Maximize Space
        uses: easimon/maximize-build-space@v10
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup cachix
        uses: cachix/cachix-action@v14
        with:
          name: isabelroses
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_TOKEN }}"

      - name: Set default git branch
        run: git config --global init.defaultBranch main

      - name: Build from the matrix
        run: nix build -L .#${{ matrix.package }}
