name: Build and populate cache

on:
  push:
    paths:
      - "modules/flake/packages/**/*"
      - "**.lock"
  workflow_dispatch:
  workflow_run:
    workflows:
      - Bump Flake Inputs
    types:
      - completed

jobs:
  build:
    name: Build (${{ matrix.system }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: aarch64-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          source-url: https://install.lix.systems/lix/lix-installer-${{ matrix.system }}
          logger: pretty
          diagnostic-endpoint: ""

      - name: Setup cachix
        uses: cachix/cachix-action@v15
        with:
          name: isabelroses
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_TOKEN }}"

      - name: Build from the lix
        run: nix build -L .#lix
