name: Build and populate cache

on:
  workflow_dispatch:
  push:
    paths:
      - "flake/pkgs"
      - "**.lock"
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - bellado
          - izrss
          - zzz
          - gh-eco
          - isabelroses-website

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup cachix
        uses: cachix/cachix-action@v14
        with:
          name: isabelroses
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_TOKEN }}"

      - name: Build from the matrix
        run: nix build -L .#${{ matrix.package }}
