name: Build and populate cache

on:
  workflow_dispatch:
  push:
    paths:
      - "flake/pkgs"
      - "**.lock"
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - bellado
          - isabelroses-website
          - catppuccinifier-cli
          - lutgen-rs
          - patched-gjs
          - plymouth-theme-catppuccin

    steps:
      - name: Prepare Environment
        uses: ./.github/runners/build-common.yml
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup cachix
        uses: cachix/cachix-action@v14
        with:
          name: isabelroses
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_TOKEN }}"

      - name: Set default git branch
        run: git config --global init.defaultBranch main

      - name: Build from the matrix
        run: nix build -L .#${{ matrix.package }}
