name: Build and populate cache

on:
  push:
    paths:
      - "modules/flake/packages/**/*"
      - "**.lock"
      - ".github/actions/**/*"
      - ".github/workflows/build.yml"
  workflow_dispatch:
  workflow_run:
    workflows:
      - Bump Flake Inputs
    types:
      - completed

jobs:
  build:
    name: Build (${{ matrix.system }})
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: aarch64-darwin
          - os: ubuntu-24.04-arm
            system: aarch64-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: ./.github/actions/install-lix

      - name: Setup Attic
        uses: ryanccn/attic-action@v0.3.1
        with:
          endpoint: https://cache.tgirl.cloud
          cache: tgirlcloud
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Build from the lix
        run: nix build -L .#lix
