name: Build and Release ISO Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 1,15 * *" # Run on the 1st and 15th of every month at 3:00 AM

jobs:
  build-isos:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize Space
        uses: easimon/maximize-build-space@v10
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-codeql: true
          remove-haskell: true
          remove-docker-images: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_GIT }}

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          logger: pretty

      - name: Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build Lilith Iso
        continue-on-error: false
        run: nix run nixpkgs#nix-fast-build -- --skip-cached --no-nom --flake .#images.lilith --out-link lilith

      - name: Upload Release Artifacts
        run: |
          release=$(date +"%Y-%m-%d")
          gh release create "$release"
          gh release upload "$release" ./lilith-/iso/*.iso
        env:
          GH_TOKEN: ${{ github.token }}
