name: Validate Nix Flake

on:
  workflow_dispatch:
  push:
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"

jobs:
  check-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: Check Flake
        run: NIXPKGS_ALLOW_UNFREE=1 nix flake check --accept-flake-config --impure

      - name: Check Flake Inputs
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          send-statistics: false
