name: Validate Nix Flake

on:
  workflow_dispatch:
  push:
    paths:
      - "**.nix"
      - "**.lock"
      - ".github/workflows/check.yml"

jobs:
  check-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Environment
        uses: ./.github/runners/common.yml
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check Flake
        run: nix flake check --accept-flake-config

      - name: Check Flake Inputs
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          send-statistics: false
