name: Build and deploy docs

on:
  workflow_dispatch:
  push:
    paths:
      - "modules/extra/**/*"
      - "docs/*"

jobs:
  build:
    name: Build and deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Build Linux packages
        run: "nix build -L .#docs-html"

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
