name: Build and deploy docs

on:
  workflow_dispatch:
  push:
    paths:
      - "docs/**/*"
      - ".github/workflows/docs.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          logger: pretty
          diagnostic-endpoint: ""
          extra-conf: |
            substituters = https://nix-community.cachix.org https://isabelroses.cachix.org https://catppuccin.cachix.org https://cache.nixos.org/
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= isabelroses.cachix.org-1:mXdV/CMcPDaiTmkQ7/4+MzChpOe6Cb97njKmBQQmLPM= catppuccin.cachix.org-1:noG/4HkbhJb+lUAdKrph6LaozJvAeEEZj4N732IysmU=

      - name: Build Linux packages
        run: "nix build -L .#docs"

      - name: Upload Pages Artifact
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: "result/"

  deploy:
    needs: "build"
    runs-on: "ubuntu-latest"

    permissions:
      pages: "write"
      id-token: "write"

    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"

    steps:
      - name: "Deploy to GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v4"
