name: Bump Flake Inputs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2,4,6"

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Environment
        uses: ./.github/runners/common.yml
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Lockfile
        uses: DeterminateSystems/update-flake-lock@main
        id: update
        with:
          pr-title: "bump: flake inputs"
          commit-msg: "bump: flake inputs"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Changes
        run: gh pr merge ${{ steps.update.outputs.pull-request-number }} --squash --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
