name: Bump Flake Inputs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./.github/actions/setup
        with:
          optimise-space: true

      - name: Update Lockfile
        uses: DeterminateSystems/update-flake-lock@main
        id: update
        with:
          pr-title: "chore(deps): flake inputs"
          commit-msg: "chore(deps): flake inputs"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Changes
        run: gh pr merge ${{ steps.update.outputs.pull-request-number }} --squash --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
