name: Bump Flake Inputs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    outputs:
      pr: ${{ steps.pr.outputs.pull-request-url }}
      branch: ${{ steps.pr.outputs.pull-request-branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: ./.github/actions/install-lix

      - name: Update Lockfile
        run: nix flake update

      - name: Create Pull request
        id: pr
        uses: peter-evans/create-pull-request@v7
        with:
          title: "chore: update flake inputs"
          commit-message: "chore: update flake inputs"
          branch: update-flake-inputs

  check-flake:
    name: Check (${{ matrix.system }})
    needs: update-lockfile
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: aarch64-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.update-lockfile.outputs.branch }}

      - name: Check Flake
        uses: ./.github/actions/check
        with:
          ref: ${{ needs.update-lockfile.outputs.branch }}

  merge:
    name: Merge Pull Request
    needs: [update-lockfile, check-flake]
    runs-on: ubuntu-latest

    steps:
      - name: Merge Pull Request
        run: gh pr merge --rebase --auto --delete-branch ${{ needs.update-lockfile.outputs.pr }}
        env:
          GH_TOKEN: ${{ github.token }}

