name: Bump Flake Inputs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          logger: pretty
          diagnostic-endpoint: ""
          extra-conf: |
            substituters = https://nix-community.cachix.org https://isabelroses.cachix.org https://catppuccin.cachix.org https://cache.nixos.org/
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= isabelroses.cachix.org-1:mXdV/CMcPDaiTmkQ7/4+MzChpOe6Cb97njKmBQQmLPM= catppuccin.cachix.org-1:noG/4HkbhJb+lUAdKrph6LaozJvAeEEZj4N732IysmU=

      - name: Update Lockfile
        run: nix flake update

      - name: Commit and Push
        uses: endbug/add-and-commit@v9
        with:
          message: "chore: update flake inputs"
